import { db } from '../firebase';
import { collection, doc, setDoc } from 'firebase/firestore';

const staffData = [
  {
    id: 'staff1',
    name: 'Rajesh Kumar',
    designation: 'General Manager',
    salary: 120000,
    branch: 'Coorg',
    photo: '/src/assets/images/Master_Suite.jpg',
    email: 'rajesh.kumar@solacestay.com',
    phone: '+91 98765 43210',
    address: '123 MG Road, Coorg, Karnataka',
    city: 'Coorg',
    state: 'Karnataka',
    gender: 'Male',
    age: 45,
    joiningDate: '2020-01-15',
    department: 'Management',
    shift: 'Day',
    emergencyContact: '+91 98765 43211',
    bloodGroup: 'O+',
    education: 'MBA in Hospitality Management',
    experience: '15 years'
  },
  {
    id: 'staff2',
    name: 'Priya Sharma',
    designation: 'Executive Chef',
    salary: 95000,
    branch: 'Mumbai',
    photo: '/src/assets/images/Deluxe.jpg',
    email: 'priya.sharma@solacestay.com',
    phone: '+91 98765 43212',
    address: '456 Juhu Beach Road, Mumbai, Maharashtra',
    city: 'Mumbai',
    state: 'Maharashtra',
    gender: 'Female',
    age: 38,
    joiningDate: '2019-06-20',
    department: 'Kitchen',
    shift: 'Day',
    emergencyContact: '+91 98765 43213',
    bloodGroup: 'A+',
    education: 'Diploma in Culinary Arts',
    experience: '12 years'
  },
  {
    id: 'staff3',
    name: 'Amit Patel',
    designation: 'Head Chef',
    salary: 100000,
    branch: 'Ahmedabad',
    photo: '/src/assets/images/Standard.jpg',
    email: 'amit.patel@solacestay.com',
    phone: '+91 98765 43214',
    address: '789 CG Road, Ahmedabad, Gujarat',
    city: 'Ahmedabad',
    state: 'Gujarat',
    gender: 'Male',
    age: 42,
    joiningDate: '2021-03-10',
    department: 'Kitchen',
    shift: 'Day',
    emergencyContact: '+91 98765 43215',
    bloodGroup: 'B+',
    education: 'Bachelors in Hotel Management',
    experience: '10 years'
  },
  {
    id: 'staff4',
    name: 'Meera Desai',
    designation: 'Receptionist',
    salary: 50000,
    branch: 'Ahmedabad',
    photo: '/src/assets/images/Standard.jpg',
    email: 'meera.desai@solacestay.com',
    phone: '+91 98765 43216',
    address: '234 SG Highway, Ahmedabad, Gujarat',
    city: 'Ahmedabad',
    state: 'Gujarat',
    gender: 'Female',
    age: 28,
    joiningDate: '2022-01-05',
    department: 'Front Office',
    shift: 'Day',
    emergencyContact: '+91 98765 43217',
    bloodGroup: 'A-',
    education: 'Bachelor in Hotel Management',
    experience: '4 years'
  },
  {
    id: 'staff5',
    name: 'Suresh Menon',
    designation: 'Chef',
    salary: 80000,
    branch: 'Mumbai',
    photo: '/src/assets/images/Deluxe.jpg',
    email: 'suresh.menon@solacestay.com',
    phone: '+91 98765 43218',
    address: '567 Marine Drive, Mumbai, Maharashtra',
    city: 'Mumbai',
    state: 'Maharashtra',
    gender: 'Male',
    age: 35,
    joiningDate: '2021-08-15',
    department: 'Kitchen',
    shift: 'Night',
    emergencyContact: '+91 98765 43219',
    bloodGroup: 'O-',
    education: 'Diploma in Culinary Arts',
    experience: '8 years'
  },
  {
    id: 'staff6',
    name: 'Anjali Gupta',
    designation: 'Housekeeping Manager',
    salary: 70000,
    branch: 'Coorg',
    photo: '/src/assets/images/Master_Suite.jpg',
    email: 'anjali.gupta@solacestay.com',
    phone: '+91 98765 43220',
    address: '890 Coffee Estate Road, Coorg, Karnataka',
    city: 'Coorg',
    state: 'Karnataka',
    gender: 'Female',
    age: 32,
    joiningDate: '2021-04-01',
    department: 'Housekeeping',
    shift: 'Day',
    emergencyContact: '+91 98765 43221',
    bloodGroup: 'B-',
    education: 'Diploma in Hotel Management',
    experience: '6 years'
  },
  {
    id: 'staff7',
    name: 'Vikram Shah',
    designation: 'Sales & Marketing Manager',
    salary: 100000,
    branch: 'Mumbai',
    photo: '/src/assets/images/Deluxe.jpg',
    email: 'vikram.shah@solacestay.com',
    phone: '+91 98765 43222',
    address: '123 Bandra West, Mumbai, Maharashtra',
    city: 'Mumbai',
    state: 'Maharashtra',
    gender: 'Male',
    age: 36,
    joiningDate: '2020-09-15',
    department: 'Sales',
    shift: 'Day',
    emergencyContact: '+91 98765 43223',
    bloodGroup: 'AB+',
    education: 'MBA in Marketing',
    experience: '9 years'
  },
  {
    id: 'staff8',
    name: 'Neha Reddy',
    designation: 'Front Office Manager',
    salary: 80000,
    branch: 'Coorg',
    photo: '/src/assets/images/Master_Suite.jpg',
    email: 'neha.reddy@solacestay.com',
    phone: '+91 98765 43224',
    address: '456 Hill View Road, Coorg, Karnataka',
    city: 'Coorg',
    state: 'Karnataka',
    gender: 'Female',
    age: 30,
    joiningDate: '2021-11-01',
    department: 'Front Office',
    shift: 'Day',
    emergencyContact: '+91 98765 43225',
    bloodGroup: 'A+',
    education: 'Bachelor in Hospitality',
    experience: '5 years'
  },
  {
    id: 'staff9',
    name: 'Arjun Nair',
    designation: 'Maintenance Supervisor',
    salary: 70000,
    branch: 'Ahmedabad',
    photo: '/src/assets/images/Standard.jpg',
    email: 'arjun.nair@solacestay.com',
    phone: '+91 98765 43226',
    address: '789 Satellite Road, Ahmedabad, Gujarat',
    city: 'Ahmedabad',
    state: 'Gujarat',
    gender: 'Male',
    age: 40,
    joiningDate: '2020-03-20',
    department: 'Maintenance',
    shift: 'Day',
    emergencyContact: '+91 98765 43227',
    bloodGroup: 'B+',
    education: 'Diploma in Engineering',
    experience: '12 years'
  },
  {
    id: 'staff10',
    name: 'Pooja Patel',
    designation: 'Guest Experience Manager',
    salary: 70000,
    branch: 'Mumbai',
    photo: '/src/assets/images/Deluxe.jpg',
    email: 'pooja.patel@solacestay.com',
    phone: '+91 98765 43228',
    address: '234 Powai, Mumbai, Maharashtra',
    city: 'Mumbai',
    state: 'Maharashtra',
    gender: 'Female',
    age: 33,
    joiningDate: '2021-06-15',
    department: 'Guest Services',
    shift: 'Day',
    emergencyContact: '+91 98765 43229',
    bloodGroup: 'O+',
    education: 'Bachelor in Hotel Management',
    experience: '7 years'
  },
  {
    id: 'staff11',
    name: 'Karthik Menon',
    designation: 'Restaurant Manager',
    salary: 90000,
    branch: 'Coorg',
    photo: '/src/assets/images/Master_Suite.jpg',
    email: 'karthik.menon@solacestay.com',
    phone: '+91 98765 43230',
    address: '567 Valley View, Coorg, Karnataka',
    city: 'Coorg',
    state: 'Karnataka',
    gender: 'Male',
    age: 34,
    joiningDate: '2020-12-01',
    department: 'Food & Beverage',
    shift: 'Day',
    emergencyContact: '+91 98765 43231',
    bloodGroup: 'AB-',
    education: 'Hotel Management Degree',
    experience: '8 years'
  },
  {
    id: 'staff12',
    name: 'Sanya Kapoor',
    designation: 'Event Coordinator',
    salary: 60000,
    branch: 'Ahmedabad',
    photo: '/src/assets/images/Standard.jpg',
    email: 'sanya.kapoor@solacestay.com',
    phone: '+91 98765 43232',
    address: '890 Vastrapur, Ahmedabad, Gujarat',
    city: 'Ahmedabad',
    state: 'Gujarat',
    gender: 'Female',
    age: 27,
    joiningDate: '2022-02-15',
    department: 'Events',
    shift: 'Day',
    emergencyContact: '+91 98765 43233',
    bloodGroup: 'B+',
    education: 'Bachelor in Event Management',
    experience: '3 years'
  },
  {
    id: 'staff13',
    name: 'Rahul Verma',
    designation: 'Security Manager',
    salary: 70000,
    branch: 'Mumbai',
    photo: '/src/assets/images/Deluxe.jpg',
    email: 'rahul.verma@solacestay.com',
    phone: '+91 98765 43234',
    address: '123 Andheri East, Mumbai, Maharashtra',
    city: 'Mumbai',
    state: 'Maharashtra',
    gender: 'Male',
    age: 38,
    joiningDate: '2020-07-01',
    department: 'Security',
    shift: 'Night',
    emergencyContact: '+91 98765 43235',
    bloodGroup: 'O+',
    education: 'Security Management Certification',
    experience: '10 years'
  },
  {
    id: 'staff14',
    name: 'Maya Iyer',
    designation: 'Guest Relations Manager',
    salary: 70000,
    branch: 'Coorg',
    photo: '/src/assets/images/Master_Suite.jpg',
    email: 'maya.iyer@solacestay.com',
    phone: '+91 98765 43236',
    address: '456 Estate View, Coorg, Karnataka',
    city: 'Coorg',
    state: 'Karnataka',
    gender: 'Female',
    age: 29,
    joiningDate: '2021-09-01',
    department: 'Guest Relations',
    shift: 'Day',
    emergencyContact: '+91 98765 43237',
    bloodGroup: 'A+',
    education: 'MBA in Hospitality',
    experience: '5 years'
  },
  {
    id: 'staff15',
    name: 'Aditya Singh',
    designation: 'Operations Manager',
    salary: 80000,
    branch: 'Ahmedabad',
    photo: '/src/assets/images/Standard.jpg',
    email: 'aditya.singh@solacestay.com',
    phone: '+91 98765 43238',
    address: '789 Bodakdev, Ahmedabad, Gujarat',
    city: 'Ahmedabad',
    state: 'Gujarat',
    gender: 'Male',
    age: 31,
    joiningDate: '2021-01-15',
    department: 'Operations',
    shift: 'Day',
    emergencyContact: '+91 98765 43239',
    bloodGroup: 'B+',
    education: 'Bachelor in Hotel Management',
    experience: '6 years'
  }
];

export const initializeStaffData = async () => {
  try {
    const staffCollection = collection(db, 'staff');
    
    for (const staff of staffData) {
      await setDoc(doc(staffCollection, staff.id), staff);
    }
    
    console.log('Staff data initialized successfully');
  } catch (error) {
    console.error('Error initializing staff data:', error);
  }
}; 